language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt-get update -qq
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # perf
  - sudo apt-get install -qq linux-tools-4.15.0-1037-gcp linux-tools-4.15.0-1040-gcp linux-cloud-tools-4.15.0-1040-gcp
  # linux-cloud-tools-4.15.0-1037-gcp linux-tools-gcp linux-cloud-tools-gcp

script: 
  # Build
  - qmake
  - make release --silent
  # Run
  - sudo perf record -g ./travis_qmake_gcc_cpp14_perf
  # Produce the perf log
  - sudo perf report --stdio -g 'graph,0.5,caller' > perf.log
  # Show the perf log
  - cat perf.log
