language: cpp
dist: bionic
compiler: gcc

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # perf
  - sudo apt-get install libgoogle-perftools-dev
  # linux-tools-3.13.0-92-generic linux-tools-4.4.0-101-generic linux-cloud-tools-4.4.0-101-generic

script: 
  # Build
  - qmake
  - make release --silent
  # Run
  - sudo perf record -g ./travis_qmake_gcc_cpp14_perf
  # Produce the perf log
  - sudo perf report --stdio -g 'graph,0.5,caller' > perf.log
  # Show the perf log
  - cat perf.log
